(ns crawl.enums)

(def input-modes
  [:normal
   :command
   :target
   :target-dir
   :target-path
   :more
   :macro
   :prompt
   :yesno])

(def equip
  [:weapon
   :cloak
   :helmet
   :gloves
   :boots
   :shield
   :body-armour
   :left-ring
   :right-ring
   :amulet
   :ring-one
   :ring-two
   :ring-three
   :ring-four
   :ring-five
   :ring-six
   :ring-seven
   :ring-eight])

(def dungeon-features
  [:unseen
   :closed-door
   :runed-door
   :old-secret-door
   :mangrove
   :metal-wall
   :green-crystal-wall
   :rock-wall
   :slimy-wall
   :stone-wall
   :permarock-wall
   :clear-rock-wall
   :clear-stone-wall
   :clear-permarock-wall
   :grate
   :tree
   :open-sea
   :lava-sea
   :orcish-idol
   :granite-statue
   :malign-gateway
   nil
   nil
   nil
   nil
   nil
   nil
   nil
   nil
   nil
   :lava      ; = 30
   :deep-water
   :shallow-water
   :floor
   :open-door
   :trap-mechanical
   :trap-magical
   :trap-natural
   :trap-web
   :undiscovered-trap
   :enter-shop
   :abandoned-shop
   :stone-stairs-down-i
   :stone-stairs-down-ii
   :stone-stairs-down-iii
   :escape-hatch-down
   :stone-stairs-up-i
   :stone-stairs-up-ii
   :stone-stairs-up-iii
   :escape-hatch-up
   :enter-dis
   :enter-gehenna
   :enter-cocytus
   :enter-tartarus
   :enter-abyss
   :exit-abyss
   :stone-arch
   :enter-pandemonium
   :exit-pandemonium
   :transit-pandemonium
   :exit-dungeon
   :exit-through-abyss
   :exit-hell
   :enter-hell
   :enter-labyrinth
   :teleporter
   :enter-portal-vault
   :exit-portal-vault
   :expired-portal
   :enter-dwarven-hall
   :enter-orcish-mines
   :enter-lair
   :enter-slime-pits
   :enter-vaults
   :enter-crypt
   :enter-hall-of-blades
   :enter-zot
   :enter-temple
   :enter-snake-pit
   :enter-elven-halls
   :enter-tomb
   :enter-swamp
   :enter-shoals
   :enter-spider-nest
   :enter-forest
   :unused-enter-branch-1
   :return-from-dwarven-hall
   :return-from-orcish-mines
   :return-from-lair
   :return-from-slime-pits
   :return-from-vaults
   :return-from-crypt
   :return-from-hall-of-blades
   :return-from-zot
   :return-from-temple
   :return-from-snake-pit
   :return-from-elven-halls
   :return-from-tomb
   :return-from-swamp
   :return-from-shoals
   :return-from-spider-nest
   :return-from-forest
   :unused-return-branch-1
   :altar-zin
   :altar-shining-one
   :altar-kikubaaqudgha
   :altar-yredelemnul
   :altar-xom
   :altar-vehumet
   :altar-okawaru
   :altar-makhleb
   :altar-sif-muna
   :altar-trog
   :altar-nemelex-xobeh
   :altar-elyvilon
   :altar-lugonu
   :altar-beogh
   :altar-jiyva
   :altar-fedhas
   :altar-cheibriados
   :altar-ashenzari
   :unused-altar-1
   :fountain-blue
   :fountain-sparkling
   :fountain-blood
   :dry-fountain-blue
   :dry-fountain-sparkling
   :dry-fountain-blood
   :permadry-fountain
   :explore-horizon
   :unknown-altar
   :unknown-portal])
